import assert from 'node:assert/strict';
import { getCompanyBankAccounts, buildCompanyBankAccountUpdate } from '../src/features/settings/companyBankAccounts.js';
const original = { bankId: 'VCB', bankName: 'Vietcombank', bankAccountName: 'CONG TY', bankAccountNumber: '001234', sepayVirtualAccountNumber: 'VA001', sepayUseVirtualAccount: true };
assert.deepEqual(getCompanyBankAccounts({}), []);
const [legacy] = getCompanyBankAccounts(original);
assert.equal(legacy.bankAccountNumber, '001234');
assert.equal(legacy.sepayVirtualAccountNumber, 'VA001');
const additional = { ...legacy, id: 'second', bankAccountNumber: '009999' };
const patch = buildCompanyBankAccountUpdate(original, additional, false);
assert.equal(patch.companyBankAccounts.length, 2);
assert.equal(patch.bankAccountNumber, undefined);
assert.equal(patch.primaryCompanyBankAccountId, legacy.id);
const changed = buildCompanyBankAccountUpdate({ ...original, ...patch }, additional, true);
assert.equal(changed.bankAccountNumber, '009999');
assert.equal(changed.primaryCompanyBankAccountId, 'second');
assert.throws(() => buildCompanyBankAccountUpdate(original, { ...legacy, id: 'duplicate' }, false));
assert.throws(() => buildCompanyBankAccountUpdate(original, { ...additional, sepayVirtualAccountNumber: '' }, false));
assert.equal(buildCompanyBankAccountUpdate({}, additional, false).bankAccountNumber, '009999');
console.log('PASS company bank accounts: legacy, additional, primary, duplicate and VA validation');
